# Classification Algorithms using scikit-learn

### k-Nearest Neighbors (k-NN)

In [37]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [38]:
dataset = sns.load_dataset('iris')
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

#### Split the dataset

In [39]:
X = dataset.iloc [:, :-1].values
y = dataset.iloc [:, 4].values

#### Split the data into training and testing sets

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [41]:
X_test

array([[6. , 3.4, 4.5, 1.6],
       [6.3, 2.5, 5. , 1.9],
       [6.4, 3.2, 4.5, 1.5],
       [5.4, 3.9, 1.7, 0.4],
       [7.7, 3.8, 6.7, 2.2],
       [5.1, 3.7, 1.5, 0.4],
       [6.3, 2.5, 4.9, 1.5],
       [6. , 2.2, 5. , 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.7, 1.5, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [4.7, 3.2, 1.6, 0.2],
       [6.7, 3.1, 5.6, 2.4],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.1, 3.5, 1.4, 0.3],
       [4.6, 3.4, 1.4, 0.3],
       [7.7, 2.8, 6.7, 2. ],
       [5.1, 3.5, 1.4, 0.2],
       [6.7, 3. , 5.2, 2.3],
       [7.2, 3. , 5.8, 1.6],
       [6. , 2.2, 4. , 1. ],
       [5.1, 3.8, 1.9, 0.4],
       [6.4, 2.9, 4.3, 1.3],
       [6.4, 2.7, 5.3, 1.9],
       [6.7, 3. , 5. , 1.7],
       [6.9, 3.1, 5.4, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.9, 5.6, 1.8],
       [5.5, 2.4, 3.7, 1. ]])

In [42]:
X_train

array([[6.1, 3. , 4.6, 1.4],
       [5. , 3.3, 1.4, 0.2],
       [5.2, 2.7, 3.9, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [4.9, 3. , 1.4, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5.6, 2.9, 3.6, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.7, 2.8, 4.1, 1.3],
       [7.2, 3.2, 6. , 1.8],
       [5.7, 2.8, 4.5, 1.3],
       [5.7, 2.9, 4.2, 1.3],
       [5. , 3.5, 1.6, 0.6],
       [6.2, 2.9, 4.3, 1.3],
       [6.2, 3.4, 5.4, 2.3],
       [5.7, 2.5, 5. , 2. ],
       [5.6, 2.8, 4.9, 2. ],
       [7.9, 3.8, 6.4, 2. ],
       [5.4, 3.4, 1.7, 0.2],
       [6.9, 3.2, 5.7, 2.3],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [7.4, 2.8, 6.1, 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.7, 3.1, 4.7, 1.5],
       [4.8, 3. , 1.4, 0.3],
       [6.4, 3.1, 5.5, 1.8],
       [6.9, 3.1, 5.1, 2.3],
       [4.8, 3. , 1.4, 0.1],
       [5.6, 3. , 4.5, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [4.7, 3.2, 1.3, 0.2],
       [6.3, 2.3, 4.4, 1.3],
       [5. , 3.4, 1.5, 0.2],
       [4.9, 3

In [43]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [44]:
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

#### Prediction

In [45]:
y_pred = classifier.predict(X_test)

In [46]:
y_pred

array(['versicolor', 'virginica', 'versicolor', 'setosa', 'virginica',
       'setosa', 'virginica', 'versicolor', 'setosa', 'setosa', 'setosa',
       'setosa', 'virginica', 'setosa', 'setosa', 'setosa', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'virginica',
       'versicolor', 'virginica', 'versicolor'], dtype=object)

In [49]:
print(classification_report (y_test, y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        12
  versicolor       0.75      0.86      0.80         7
   virginica       0.90      0.82      0.86        11

    accuracy                           0.90        30
   macro avg       0.88      0.89      0.89        30
weighted avg       0.90      0.90      0.90        30



In [50]:
print(confusion_matrix (y_test, y_pred))

[[12  0  0]
 [ 0  6  1]
 [ 0  2  9]]


### Support Vector Machine (SVM)

In [51]:
from sklearn.svm import SVC

In [52]:
bankdata = pd.read_csv ('banknote.csv')

In [53]:
bankdata.shape

(1372, 5)

In [54]:
bankdata.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

#### Data preprocessing

In [56]:
X = bankdata.drop('class', axis = 1)
y = bankdata['class']

In [57]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

#### Training the Algorithm

In [59]:
svclassifier = SVC(kernel = 'linear')
svclassifier.fit (X_train, y_train)

SVC(kernel='linear')

#### Prediction

In [60]:
y_pred = svclassifier.predict(X_test)
y_pred

array([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0], dtype=int64)

#### Evaluate the Model

In [63]:
print (classification_report (y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98       161
           1       0.97      0.99      0.98       114

    accuracy                           0.98       275
   macro avg       0.98      0.98      0.98       275
weighted avg       0.98      0.98      0.98       275



### Random Forest Algorithm

In [68]:
import pandas as pd
import numpy as np

In [69]:
dataset = pd.read_csv ('banknote.csv')
dataset.head()

variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

#### Split the data

In [70]:
X = dataset.iloc [:, :-1].values
y = dataset.iloc [:, 4].values

#### Split the data into training and testing sets

In [72]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

#### Scaling data

In [73]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [78]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 20, random_state = 0)
classifier.fit (X_train, y_train)
y_pred = classifier.predict(X_test)

In [80]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))

[[138   0]
 [  1 136]]


In [81]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       138
           1       1.00      0.99      1.00       137

    accuracy                           1.00       275
   macro avg       1.00      1.00      1.00       275
weighted avg       1.00      1.00      1.00       275



In [82]:
print(accuracy_score(y_test, y_pred))

0.9963636363636363


### Lets write the code altogether 

#### Load and Prepare the Dataset

In [88]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the dataset
dataset = sns.load_dataset('exercise')
dataset.head()

# Display the first few rows of the dataset
dataset.head()

# Convert 'time' to numeric by stripping ' min' and converting to int
dataset ['time'] = dataset ['time'].str.replace(' min', '').astype(int)

X = dataset[['id', 'time']].values
y = dataset['pulse'].values

# Standardize the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


### Apply Classification Algorithms

In [89]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

# Define a dictionary of classifiers
classifiers = {
    "Logistic Regression": LogisticRegression(),
    "k-Nearest Neighbors": KNeighborsClassifier(),
    "Support Vector Machine": SVC(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "Naive Bayes": GaussianNB()
}

# Train and evaluate each classifier
for name, clf in classifiers.items():
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy: {accuracy:.2f}")
    print(classification_report(y_test, y_pred))
    print("\n" + "="*50 + "\n")


Logistic Regression Accuracy: 0.00
              precision    recall  f1-score   support

          82       0.00      0.00      0.00       1.0
          83       0.00      0.00      0.00       0.0
          84       0.00      0.00      0.00       0.0
          85       0.00      0.00      0.00       1.0
          87       0.00      0.00      0.00       1.0
          90       0.00      0.00      0.00       0.0
          91       0.00      0.00      0.00       1.0
          92       0.00      0.00      0.00       1.0
          93       0.00      0.00      0.00       0.0
          94       0.00      0.00      0.00       1.0
          95       0.00      0.00      0.00       2.0
          96       0.00      0.00      0.00       2.0
          97       0.00      0.00      0.00       1.0
          98       0.00      0.00      0.00       1.0
          99       0.00      0.00      0.00       0.0
         100       0.00      0.00      0.00       1.0
         103       0.00      0.00      0.00   

C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_cla

Random Forest Accuracy: 0.06
              precision    recall  f1-score   support

          80       0.00      0.00      0.00         0
          82       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         0
          84       0.00      0.00      0.00         0
          85       0.00      0.00      0.00         1
          87       0.00      0.00      0.00         1
          88       0.00      0.00      0.00         0
          89       0.00      0.00      0.00         0
          90       0.00      0.00      0.00         0
          91       0.00      0.00      0.00         1
          92       0.00      0.00      0.00         1
          94       0.00      0.00      0.00         1
          95       0.00      0.00      0.00         2
          96       0.50      0.50      0.50         2
          97       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         1
          99       0.00      0.00      0.00         

C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_cla

Gradient Boosting Accuracy: 0.11
              precision    recall  f1-score   support

          80       0.00      0.00      0.00         0
          82       0.00      0.00      0.00         1
          85       1.00      1.00      1.00         1
          87       0.00      0.00      0.00         1
          88       0.00      0.00      0.00         0
          91       0.00      0.00      0.00         1
          92       0.33      1.00      0.50         1
          94       0.00      0.00      0.00         1
          95       0.00      0.00      0.00         2
          96       0.00      0.00      0.00         2
          97       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         1
          99       0.00      0.00      0.00         0
         100       0.00      0.00      0.00         1
         101       0.00      0.00      0.00         0
         103       0.00      0.00      0.00         1
         104       0.00      0.00      0.00     

C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_cla

# One by one Implementation

In [90]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [91]:
dataset = sns.load_dataset('exercise')
dataset.head()

Unnamed: 0  id     diet  pulse    time  kind
0           0   1  low fat     85   1 min  rest
1           1   1  low fat     85  15 min  rest
2           2   1  low fat     88  30 min  rest
3           3   2  low fat     90   1 min  rest
4           4   2  low fat     92  15 min  rest

#### Convert 'time' to numeric by stripping ' min' and converting to int

In [92]:
dataset ['time'] = dataset ['time'].str.replace(' min', '').astype(int)

In [93]:
X = dataset[['id', 'time']].values
y = dataset['pulse'].values

#### Standardize the features

In [94]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

#### Split the data into training and testing sets

In [96]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

### Logistic Regression

In [97]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

#### Train the Logistic Regression model

In [98]:
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

LogisticRegression()

#### Make predictions

In [100]:
y_pred_log_reg = log_reg.predict(X_test)
y_pred_log_reg

array([ 93,  90, 100,  99,  97,  90,  97, 140,  83, 100,  98,  84, 140,
       140,  97,  83,  97,  90], dtype=int64)

#### Evaluate the model

In [103]:
accuracy_log_reg = accuracy_score(y_test, y_pred_log_reg)

In [104]:
print(f"Logistic Regression Accuracy: {accuracy_log_reg:.2f}")
print(classification_report(y_test, y_pred_log_reg))

Logistic Regression Accuracy: 0.00
              precision    recall  f1-score   support

          82       0.00      0.00      0.00       1.0
          83       0.00      0.00      0.00       0.0
          84       0.00      0.00      0.00       0.0
          85       0.00      0.00      0.00       1.0
          87       0.00      0.00      0.00       1.0
          90       0.00      0.00      0.00       0.0
          91       0.00      0.00      0.00       1.0
          92       0.00      0.00      0.00       1.0
          93       0.00      0.00      0.00       0.0
          94       0.00      0.00      0.00       1.0
          95       0.00      0.00      0.00       2.0
          96       0.00      0.00      0.00       2.0
          97       0.00      0.00      0.00       1.0
          98       0.00      0.00      0.00       1.0
          99       0.00      0.00      0.00       0.0
         100       0.00      0.00      0.00       1.0
         103       0.00      0.00      0.00   

C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_cla

### k-Nearest Neighbors (k-NN)

#### now we need to do the same as we did for Logistic regression, Steps are same but the librarywill be different

In [110]:
from sklearn.neighbors import KNeighborsClassifier

# Train the k-NN model
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)

# Make predictions
y_pred_knn = knn.predict(X_test)

# Evaluate the model
accuracy_knn = accuracy_score(y_test, y_pred_knn)
print(f"k-Nearest Neighbors Accuracy: {accuracy_knn:.2f}")
print(classification_report(y_test, y_pred_knn))

k-Nearest Neighbors Accuracy: 0.00
              precision    recall  f1-score   support

          80       0.00      0.00      0.00       0.0
          82       0.00      0.00      0.00       1.0
          83       0.00      0.00      0.00       0.0
          84       0.00      0.00      0.00       0.0
          85       0.00      0.00      0.00       1.0
          86       0.00      0.00      0.00       0.0
          87       0.00      0.00      0.00       1.0
          89       0.00      0.00      0.00       0.0
          91       0.00      0.00      0.00       1.0
          92       0.00      0.00      0.00       1.0
          94       0.00      0.00      0.00       1.0
          95       0.00      0.00      0.00       2.0
          96       0.00      0.00      0.00       2.0
          97       0.00      0.00      0.00       1.0
          98       0.00      0.00      0.00       1.0
          99       0.00      0.00      0.00       0.0
         100       0.00      0.00      0.00   

C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_cla

### Support Vector Machine (SVM)

In [116]:
from sklearn.svm import SVC

# Train the SVM model
svm = SVC()
svm.fit(X_train, y_train)

# Make predictions
y_pred_svm = svm.predict(X_test)

# Evaluate the model
accuracy_svm = accuracy_score(y_test, y_pred_svm)
print(f"Support Vector Machine Accuracy: {accuracy_svm:.2f}")
print(classification_report(y_test, y_pred_svm))

Support Vector Machine Accuracy: 0.06
              precision    recall  f1-score   support

          82       0.00      0.00      0.00         1
          85       0.00      0.00      0.00         1
          87       0.00      0.00      0.00         1
          91       0.00      0.00      0.00         1
          92       0.00      0.00      0.00         1
          94       0.00      0.00      0.00         1
          95       0.00      0.00      0.00         2
          96       0.00      0.00      0.00         2
          97       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         1
         100       0.25      1.00      0.40         1
         103       0.00      0.00      0.00         1
         104       0.00      0.00      0.00         1
         112       0.00      0.00      0.00         1
         126       0.00      0.00      0.00         0
         130       0.00      0.00      0.00         1
         132       0.00      0.00      0.00

C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_cla

### Decision Tree

In [120]:
from sklearn.tree import DecisionTreeClassifier

# Train the Decision Tree model
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, y_train)

# Make predictions
y_pred_decision_tree = decision_tree.predict(X_test)

# Evaluate the model
accuracy_decision_tree = accuracy_score(y_test, y_pred_decision_tree)
print(f"Decision Tree Accuracy: {accuracy_decision_tree:.2f}")
print(classification_report(y_test, y_pred_decision_tree))

Decision Tree Accuracy: 0.00
              precision    recall  f1-score   support

          80       0.00      0.00      0.00       0.0
          82       0.00      0.00      0.00       1.0
          85       0.00      0.00      0.00       1.0
          87       0.00      0.00      0.00       1.0
          88       0.00      0.00      0.00       0.0
          90       0.00      0.00      0.00       0.0
          91       0.00      0.00      0.00       1.0
          92       0.00      0.00      0.00       1.0
          93       0.00      0.00      0.00       0.0
          94       0.00      0.00      0.00       1.0
          95       0.00      0.00      0.00       2.0
          96       0.00      0.00      0.00       2.0
          97       0.00      0.00      0.00       1.0
          98       0.00      0.00      0.00       1.0
          99       0.00      0.00      0.00       0.0
         100       0.00      0.00      0.00       1.0
         103       0.00      0.00      0.00       1.

C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_cla

### Random Forest

In [127]:
from sklearn.ensemble import RandomForestClassifier

# Train the Random Forest model
random_forest = RandomForestClassifier()
random_forest.fit(X_train, y_train)

# Make predictions
y_pred_random_forest = random_forest.predict(X_test)

# Evaluate the model
accuracy_random_forest = accuracy_score(y_test, y_pred_random_forest)
print(f"Random Forest Accuracy: {accuracy_random_forest:.2f}")
print(classification_report(y_test, y_pred_random_forest))

Random Forest Accuracy: 0.06
              precision    recall  f1-score   support

          80       0.00      0.00      0.00         0
          82       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         0
          84       0.00      0.00      0.00         0
          85       0.00      0.00      0.00         1
          87       0.00      0.00      0.00         1
          88       0.00      0.00      0.00         0
          89       0.00      0.00      0.00         0
          90       0.00      0.00      0.00         0
          91       0.00      0.00      0.00         1
          92       0.00      0.00      0.00         1
          94       0.00      0.00      0.00         1
          95       0.00      0.00      0.00         2
          96       0.50      0.50      0.50         2
          97       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         1
          99       0.00      0.00      0.00         

C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_cla

### Gradient Boosting

In [133]:
from sklearn.ensemble import GradientBoostingClassifier

# Train the Gradient Boosting model
gradient_boosting = GradientBoostingClassifier()
gradient_boosting.fit(X_train, y_train)

# Make predictions
y_pred_gradient_boosting = gradient_boosting.predict(X_test)

# Evaluate the model
accuracy_gradient_boosting = accuracy_score(y_test, y_pred_gradient_boosting)
print(f"Gradient Boosting Accuracy: {accuracy_gradient_boosting:.2f}")
print(classification_report(y_test, y_pred_gradient_boosting))

Gradient Boosting Accuracy: 0.11
              precision    recall  f1-score   support

          80       0.00      0.00      0.00         0
          82       0.00      0.00      0.00         1
          85       1.00      1.00      1.00         1
          87       0.00      0.00      0.00         1
          88       0.00      0.00      0.00         0
          91       0.00      0.00      0.00         1
          92       0.33      1.00      0.50         1
          94       0.00      0.00      0.00         1
          95       0.00      0.00      0.00         2
          96       0.00      0.00      0.00         2
          97       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         1
          99       0.00      0.00      0.00         0
         100       0.00      0.00      0.00         1
         101       0.00      0.00      0.00         0
         103       0.00      0.00      0.00         1
         104       0.00      0.00      0.00     

C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_cla

### Naive Bayes

In [137]:
from sklearn.naive_bayes import GaussianNB

# Train the Naive Bayes model
naive_bayes = GaussianNB()
naive_bayes.fit(X_train, y_train)

# Make predictions
y_pred_naive_bayes = naive_bayes.predict(X_test)

# Evaluate the model
accuracy_naive_bayes = accuracy_score(y_test, y_pred_naive_bayes)
print(f"Naive Bayes Accuracy: {accuracy_naive_bayes:.2f}")
print(classification_report(y_test, y_pred_naive_bayes))

Naive Bayes Accuracy: 0.06
              precision    recall  f1-score   support

          82       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         0
          84       0.00      0.00      0.00         0
          85       0.00      0.00      0.00         1
          86       0.00      0.00      0.00         0
          87       0.00      0.00      0.00         1
          88       0.00      0.00      0.00         0
          89       0.00      0.00      0.00         0
          91       0.00      0.00      0.00         1
          92       0.00      0.00      0.00         1
          94       0.00      0.00      0.00         1
          95       0.00      0.00      0.00         2
          96       0.33      0.50      0.40         2
          97       0.00      0.00      0.00         1
          98       0.00      0.00      0.00         1
         100       0.00      0.00      0.00         1
         103       0.00      0.00      0.00         1


C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Fahan\anaconda3\Lib\site-packages\sklearn\metrics\_cla