# Indexing of String

In [29]:
a = "Muslih Uddin"
print(a[-7])

h


# Slicing

In [2]:
p = "Hello students how are you?"
print(p[0:5])

Hello


In [3]:
p = "Hello students how are you?"
print(p[6:18])

students how


In [4]:
p = "Hello students how are you?"
print(p[::-1])

?uoy era woh stneduts olleH


# Indexing in NumPy Array

In [5]:
import numpy as np

array1 = np.array([10,20,30,40])
print (array1[0])

10


In [8]:
import numpy as np

array1 = np.array([10,20,30,40,50,60,70,80])
print (array1[-1])

80


In [12]:
import numpy as np

array1 = np.array([10,20,30,40])
print (array1[3:6])

[40]


In [10]:
import numpy as np

array1 = np.array([10,20,30,40])
print (array1[:5])

[10 20 30 40]


# Slicing in Numpy Arrays

In [15]:
import numpy as np

array1 = np.array([1,2,3,4,5,6,7,8,9])
print (array1[1:3])
print (array1[1:6:2])
print (array1[-1:-3:-1])
print(array1[::4])
print (array1[::-1])

[2 3]
[2 4 6]
[9 8]
[1 5 9]
[9 8 7 6 5 4 3 2 1]


### 2D Array

In [17]:
import numpy as np

array1 = np.array([[15,16,27], [25,26,27], [35,36,37], [45,46,47]])
print (array1[1, ])

[25 26 27]


In [18]:
import numpy as np

array1 = np.array([[15,16,27], [25,26,27], [35,36,37], [45,46,47]])
print (array1[1, ])
print (array1[: ,1])

[25 26 27]
[16 26 36 46]


In [19]:
import numpy as np

array1 = np.array([[15,16,27], [25,26,27], [35,36,37], [45,46,47]])
print (array1[1, ])
print (array1[: ,1])
print (array1[1:3 ,1:3])

[25 26 27]
[16 26 36 46]
[[26 27]
 [36 37]]


In [20]:
import numpy as np

array1 = np.array([[15,16,27], [25,26,27], [35,36,37], [45,46,47]])
print (array1[1, ])
print (array1[: ,1])
print (array1[1:3 ,1:3])
print (array1[1:3, ])

[25 26 27]
[16 26 36 46]
[[26 27]
 [36 37]]
[[25 26 27]
 [35 36 37]]


In [21]:
import numpy as np

array1 = np.array([[15,16,27], [25,26,27], [35,36,37], [45,46,47]])
print (array1[1, ])
print (array1[: ,1])
print (array1[1:3 ,1:3])
print (array1[1:3, ])
print (array1[: , 1:3])

[25 26 27]
[16 26 36 46]
[[26 27]
 [36 37]]
[[25 26 27]
 [35 36 37]]
[[16 27]
 [26 27]
 [36 37]
 [46 47]]


### Sub Array 

In [23]:
import numpy as np 
  
numpyArr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) 
  
# same as 3:9 or 3:n, where n is 
# the length of array 
print("Sub-Array=", numpyArr[3:]) 

Sub-Array= [4 5 6 7 8 9]


# Given a 2D array of shape (5, 5), extract a 3x3 sub-array starting from the element at position (1, 1).

In [22]:
import numpy as np

array_2d = np.array([[ 1,  2,  3,  4,  5],
                     [ 6,  7,  8,  9, 10],
                     [11, 12, 13, 14, 15],
                     [16, 17, 18, 19, 20],
                     [21, 22, 23, 24, 25]])

sub_array = array_2d[1:4, 1:4]

print("Original 2D Array:")
print(array_2d)
print("\nExtracted 3x3 Sub-array:")
print(sub_array)

Original 2D Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Extracted 3x3 Sub-array:
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


# From a 3D array of shape (4, 3, 2), extract all elements in the first two rows and all columns of the second slice along the third axis

In [24]:
import numpy as np

array_3d = np.array([[[ 1,  2], [ 3,  4], [ 5,  6]],
                     [[ 7,  8], [ 9, 10], [11, 12]],
                     [[13, 14], [15, 16], [17, 18]],
                     [[19, 20], [21, 22], [23, 24]]])

# Extract all elements in the first two rows and all columns of the second slice along the third axis
sub_array = array_3d[:2, :, 1]

print("Original 3D Array:")
print(array_3d)
print("\nExtracted Sub-array:")
print(sub_array)

Original 3D Array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]

Extracted Sub-array:
[[ 2  4  6]
 [ 8 10 12]]


# Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 7]

In [25]:
import numpy as np

array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Use fancy indexing to extract elements at positions [1, 3, 4, 7]
indices = [1, 3, 4, 7]
extracted_elements = array[indices]

print("Original Array:")
print(array)
print("\nExtracted Elements:")
print(extracted_elements)

Original Array:
[ 10  20  30  40  50  60  70  80  90 100]

Extracted Elements:
[20 40 50 80]


# Mini Project Using Array Operations, Indexing, and Slicing 

In [28]:
header = """
************************************************************
*                                                          *
*          <== Temperature Data Analysis ==>               *
*                                                          *
************************************************************
"""

print(header)

import numpy as np

# Create a 1D array of temperatures for 30 days
temperatures = np.array([23, 25, 22, 20, 21, 24, 26, 27, 30, 28, 29, 31, 32, 33, 34, 35, 30, 28, 27, 25, 26, 22, 23, 24, 25, 28, 29, 27, 26, 25])

# Calculate the average temperature of the month
average_temp = np.mean(temperatures)
print("Average Temperature of the Month:", average_temp)

# Find the hottest and coldest days
hottest_day = np.argmax(temperatures) + 1  # +1 to convert to 1-based index
coldest_day = np.argmin(temperatures) + 1  # +1 to convert to 1-based index
print("Hottest Day:", hottest_day, "with temperature:", temperatures[hottest_day - 1])
print("Coldest Day:", coldest_day, "with temperature:", temperatures[coldest_day - 1])

# Extract the temperatures of the first week
first_week_temps = temperatures[:7]
print("Temperatures of the First Week:", first_week_temps)

# Find the number of days with temperatures above 30 degrees
days_above_30 = np.sum(temperatures > 30)
print("Number of Days with Temperatures Above 30 Degrees:", days_above_30)

# Additional Analysis: Find temperatures in the second week
second_week_temps = temperatures[7:14]
print("Temperatures of the Second Week:", second_week_temps)

# Additional Analysis: Find the temperature range (difference between the max and min)
temperature_range = np.ptp(temperatures)
print("Temperature Range of the Month:", temperature_range)


************************************************************
*                                                          *
*          <== Temperature Data Analysis ==>               *
*                                                          *
************************************************************

Average Temperature of the Month: 26.833333333333332
Hottest Day: 16 with temperature: 35
Coldest Day: 4 with temperature: 20
Temperatures of the First Week: [23 25 22 20 21 24 26]
Number of Days with Temperatures Above 30 Degrees: 5
Temperatures of the Second Week: [27 30 28 29 31 32 33]
Temperature Range of the Month: 15
