In [1]:
import numpy as np

In [5]:
mat = np.array([[1,2], [3,4]])

In [6]:
mat

array([[1, 2],
       [3, 4]])

### Determinant

In [7]:
np.linalg.det(mat)

-2.0000000000000004

### Inverse

In [8]:
np.linalg.inv(mat)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Transpose

In [9]:
mat.transpose()

array([[1, 3],
       [2, 4]])

### Trace

In [10]:
np.trace(mat)

5

### Multiplication

In [12]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

### Element by element multiplication

In [13]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

### True real matrix multiplication

In [14]:
arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

### Linear Equation

In [ ]:
2x + y = 1
x + y = 2

In [15]:
M0 = np.array([[2,1], [1,1]])
M1 = np.array([1,2])

In [16]:
np.linalg.solve(M0,M1)

array([-1.,  3.])

### Eigan Value

In [17]:
mat

array([[1, 2],
       [3, 4]])

In [20]:
eigvalues, eigvectors = np.linalg.eig(mat)

In [21]:
eigvalues

array([-0.37228132,  5.37228132])

In [22]:
eigvectors

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

# Assigned Tasks

### Matrix Creation and Manipulation

##### Create various types of matrices (zero matrix, identity matrix, random matrix)

In [23]:
import numpy as np

In [25]:
zero_matrix = np.zeros((3, 3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
random_matrix = np.random.random((3, 3))
random_matrix

array([[0.94308569, 0.67632911, 0.93555995],
       [0.66752188, 0.38632527, 0.613952  ],
       [0.92975984, 0.07853735, 0.61740175]])

##### Perform basic matrix operations (addition, subtraction, multiplication)

In [28]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [30]:
C = A + B
C

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [31]:
D = A - B
D

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [32]:
E = np.dot(A, B)
E

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

##### Transpose a matrix and find the determinant and inverse of a matrix:

In [33]:
A_T = A.T
A_T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
det_A = np.linalg.det(A)
det_A

-9.51619735392994e-16

In [35]:
inv_A = np.linalg.inv(A)
inv_A

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

### Solving Linear Equations

##### Solve a system of linear equations

In [ ]:
Solve Ax = b

In [36]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

In [38]:
x = np.linalg.solve(A, b)
x

array([2., 3.])

##### Implement matrix factorization methods (LU decomposition, QR decomposition)

In [39]:
from scipy.linalg import lu, qr

In [42]:
P, L, U = lu(A)
P, L, U

(array([[1., 0.],
        [0., 1.]]),
 array([[1.        , 0.        ],
        [0.33333333, 1.        ]]),
 array([[3.        , 1.        ],
        [0.        , 1.66666667]]))

In [43]:
Q, R = qr(A)
Q, R

(array([[-0.9486833 , -0.31622777],
        [-0.31622777,  0.9486833 ]]),
 array([[-3.16227766, -1.58113883],
        [ 0.        ,  1.58113883]]))

### Eigenvalues and Eigenvectors

##### Calculate the eigenvalues and eigenvectors of a given matrix

In [44]:
eigvals, eigvecs = np.linalg.eig(A)
eigvals

array([3.61803399, 1.38196601])

In [45]:
eigvecs

array([[ 0.85065081, -0.52573111],
       [ 0.52573111,  0.85065081]])

##### Verify the results by reconstructing the original matrix

In [46]:
A_reconstructed = eigvecs @ np.diag(eigvals) @ np.linalg.inv(eigvecs)
A_reconstructed

array([[3., 1.],
       [1., 2.]])

### Vector Operations

##### Perform basic vector operations (addition, dot product, cross product)

In [47]:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])

In [48]:
w = u + v
w

array([5, 7, 9])

In [49]:
dot_product = np.dot(u, v)
dot_product

32

In [50]:
cross_product = np.cross(u, v)
cross_product

array([-3,  6, -3])

##### Normalize a vector and compute vector norms

In [58]:
norm_u = np.linalg.norm(u)
normalized_u = u / norm_u

norm_u
normalized_u

array([0.26726124, 0.53452248, 0.80178373])

In [59]:
l2_norm = np.linalg.norm(u)
l1_norm = np.linalg.norm(u, 1)

In [60]:
l2_norm

3.7416573867739413

In [61]:
l1_norm

6.0

### Matrix Decomposition

##### Understand and implement Principal Component Analysis (PCA) using SVD

##### Data matrix

In [63]:
X = np.random.random((5, 3))
X

array([[0.12958996, 0.71791237, 0.42672072],
       [0.31148549, 0.62743595, 0.78944172],
       [0.87567952, 0.64100693, 0.41820305],
       [0.84337274, 0.60497796, 0.71491851],
       [0.79788244, 0.83963086, 0.20561949]])

##### Mean centering

In [65]:
X_meaned = X - np.mean(X, axis=0)
X_meaned

array([[-0.46201207,  0.03171955, -0.08425998],
       [-0.28011654, -0.05875687,  0.27846102],
       [ 0.28407749, -0.04518588, -0.09277764],
       [ 0.25177071, -0.08121485,  0.20393781],
       [ 0.20628041,  0.15343805, -0.30536121]])

##### SVD

In [66]:
U, S, Vt = np.linalg.svd(X_meaned)
U, S, Vt

(array([[-0.58891169, -0.44743267, -0.3090331 ,  0.55909139,  0.21190185],
        [-0.49444946,  0.39253089,  0.31560391, -0.27902557,  0.65113603],
        [ 0.41831236,  0.02745712, -0.68818348, -0.13621081,  0.57629072],
        [ 0.25323827,  0.58143397,  0.11832229,  0.75632282,  0.10853825],
        [ 0.41181052, -0.55398931,  0.56329038,  0.13778228,  0.43269843]]),
 array([0.70810422, 0.48437967, 0.08513948]),
 array([[ 0.95766599,  0.04814428, -0.28382736],
        [ 0.28216657, -0.35245293,  0.8922774 ],
        [ 0.05707774,  0.93459032,  0.3511169 ]]))

### Calculus Tasks

### Numerical Differentiation

##### Compute the numerical derivative of a given function

In [68]:
def f(x):
    return x**2

x = np.linspace(0, 10, 100)
h = 1e-5

##### Forward difference

In [70]:
forward_diff = (f(x + h) - f(x)) / h
forward_diff

array([1.00000000e-05, 2.02030202e-01, 4.04050404e-01, 6.06070606e-01,
       8.08090808e-01, 1.01011101e+00, 1.21213121e+00, 1.41415141e+00,
       1.61617162e+00, 1.81819182e+00, 2.02021202e+00, 2.22223222e+00,
       2.42425242e+00, 2.62627263e+00, 2.82829283e+00, 3.03031303e+00,
       3.23233323e+00, 3.43435343e+00, 3.63637364e+00, 3.83839384e+00,
       4.04041404e+00, 4.24243424e+00, 4.44445444e+00, 4.64647465e+00,
       4.84849485e+00, 5.05051505e+00, 5.25253525e+00, 5.45455545e+00,
       5.65657566e+00, 5.85859586e+00, 6.06061606e+00, 6.26263626e+00,
       6.46465646e+00, 6.66667667e+00, 6.86869687e+00, 7.07071707e+00,
       7.27273727e+00, 7.47475747e+00, 7.67677768e+00, 7.87879788e+00,
       8.08081808e+00, 8.28283828e+00, 8.48485848e+00, 8.68687869e+00,
       8.88889889e+00, 9.09091909e+00, 9.29293929e+00, 9.49495949e+00,
       9.69697970e+00, 9.89899990e+00, 1.01010201e+01, 1.03030403e+01,
       1.05050605e+01, 1.07070807e+01, 1.09091009e+01, 1.11111211e+01,
      

##### Backward difference

In [71]:
backward_diff = (f(x) - f(x - h)) / h
backward_diff

array([-1.00000000e-05,  2.02010202e-01,  4.04030404e-01,  6.06050606e-01,
        8.08070808e-01,  1.01009101e+00,  1.21211121e+00,  1.41413141e+00,
        1.61615162e+00,  1.81817182e+00,  2.02019202e+00,  2.22221222e+00,
        2.42423242e+00,  2.62625263e+00,  2.82827283e+00,  3.03029303e+00,
        3.23231323e+00,  3.43433343e+00,  3.63635364e+00,  3.83837384e+00,
        4.04039404e+00,  4.24241424e+00,  4.44443444e+00,  4.64645465e+00,
        4.84847485e+00,  5.05049505e+00,  5.25251525e+00,  5.45453545e+00,
        5.65655566e+00,  5.85857586e+00,  6.06059606e+00,  6.26261626e+00,
        6.46463646e+00,  6.66665667e+00,  6.86867687e+00,  7.07069707e+00,
        7.27271727e+00,  7.47473747e+00,  7.67675768e+00,  7.87877788e+00,
        8.08079808e+00,  8.28281828e+00,  8.48483848e+00,  8.68685869e+00,
        8.88887889e+00,  9.09089909e+00,  9.29291929e+00,  9.49493949e+00,
        9.69695970e+00,  9.89897990e+00,  1.01010001e+01,  1.03030203e+01,
        1.05050405e+01,  

##### Central difference

In [72]:
central_diff = (f(x + h) - f(x - h)) / (2 * h)
central_diff

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.5050505 , 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515151, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525252, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535353, 13.73737374, 13.93

### Numerical Integration

##### Compute the numerical integral of a given function

In [73]:
from scipy.integrate import simps

In [74]:
def g(x):
    return np.sin(x)

x = np.linspace(0, np.pi, 100)
y = g(x)

##### Trapezoidal rule

In [76]:
trapezoidal_integral = np.trapz(y, x)
trapezoidal_integral

1.9998321638939927

##### Simpson's rule

In [77]:
simpsons_integral = simps(y, x)
simpsons_integral

2.0000000534993037

### Partial Derivatives

##### Calculate partial derivatives of multivariable functions

In [78]:
def h(x, y):
    return x**2 + y**2

In [80]:
x = 1.0
y = 2.0
h_value = 0.001

h_x = (h(x + h_value, y) - h(x, y)) / h_value
h_y = (h(x, y + h_value) - h(x, y)) / h_value

In [81]:
h_x

2.0009999999999195

In [82]:
h_y

4.000999999999699

### Optimization

##### Solve optimization problems with constraints

In [83]:
from scipy.optimize import minimize

In [84]:
def objective(x):
    return x[0]**2 + x[1]**2

In [85]:
def constraint(x):
    return x[0] + x[1] - 1


In [87]:
x0 = [0.5, 0.5]
cons = {'type': 'eq', 'fun': constraint}

In [88]:
result = minimize(objective, x0, constraints=cons)
result

 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 0.5
       x: [ 5.000e-01  5.000e-01]
     nit: 1
     jac: [ 1.000e+00  1.000e+00]
    nfev: 3
    njev: 1