In [1]:
import numpy as np

array_1d = np.arange(10)
print("1D Array:", array_1d)

1D Array: [0 1 2 3 4 5 6 7 8 9]


In [4]:
import numpy as np

array_2d = np.random.randint(1, 21, size=(3, 3))
print("2D Array (3x3):\n", array_2d)

2D Array (3x3):
 [[ 3 15  3]
 [10 13  1]
 [ 8  7 15]]


In [11]:
a = {"animals", "Fruits", "Minirals", "animals", "Fruits", 1, 2, True}
print(a)

{'Fruits', 1, 2, 'Minirals', 'animals'}


In [12]:
x1 = {1,2,3}
x2 = {1.2, 1.3, 1.4}
x3 = {"a", "b", "c"}
x4 = {True, False}
print(x1,x2,x3,x4)

{1, 2, 3} {1.2, 1.3, 1.4} {'b', 'a', 'c'} {False, True}


# Dimensions in array

In [33]:
# 0 D array

arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


In [36]:
# 1D array

arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1


In [42]:
# 2D array

arr = np.array([[10,34,87,43], [6,7,8,9]])
print(arr)
print(type(arr))
print(arr.ndim)

[[10 34 87 43]
 [ 6  7  8  9]]
<class 'numpy.ndarray'>
2


In [46]:
# 3DD array

arr = np.array([[[10,34,43], [6,7,9], [90,29,46]]])
print(arr)
print(type(arr))
print(arr.ndim)

[[[10 34 43]
  [ 6  7  9]
  [90 29 46]]]
<class 'numpy.ndarray'>
3


In [47]:
a = np.array(42)
b = np.array([1,2,3])
c = np.array([[4,5,6], [7,8,9]])
d = np.array([[[10,11,12],[13,14,15], [16,17,18]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# Slicing of numpy arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([2,3,4,5,6,7])
print(arr[1:5])

[3 4 5 6]


In [3]:
arr = np.array([2,3,4,5,6,7])
print(arr[::2])

[2 4 6]


In [7]:
a = np.array([[12,12,13,14,15], [1,2,3,4,5]])
print(a[1, 1:4])

[2 3 4]


Data types in numpy
Numpy has some extra data types, and refer to data types with one character, like;

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type (void)

# Create a 1D NumPy array containing the integers from 0 to 9

In [6]:
import numpy as np

array_1d = np.arange(10)
print("1D Array:", array_1d)

1D Array: [0 1 2 3 4 5 6 7 8 9]


# Create a 2D NumPy array (3x3) containing random integers between 1 and 20.

In [7]:
import numpy as np

array_2d = np.random.randint(1, 21, size=(3, 3))
print("2D Array (3x3):\n", array_2d)

2D Array (3x3):
 [[10  6 12]
 [ 2 17  6]
 [16 13 15]]


# Create a 3D NumPy array with dimensions (2, 3, 4) filled with ones.

In [11]:
array_3d = np.ones((2, 3, 4))
print("3D Array (2x3x4):\n", array_3d)

3D Array (2x3x4):
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


# Add two 1D arrays element-wise

In [12]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

array_sum = np.add(array_a, array_b)
print("Sum of 1D arrays:", array_sum)

Sum of 1D arrays: [5 7 9]


# Multiply two 2D arrays element-wise

In [14]:
array_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

array_product = np.multiply(array_a, array_b)
print("Element-wise product of 2D arrays:\n", array_product)

Element-wise product of 2D arrays:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


# Calculate the dot product of two matrices

In [15]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

dot_product = np.dot(matrix_a, matrix_b)
print("Dot product of matrices:\n", dot_product)

Dot product of matrices:
 [[19 22]
 [43 50]]


# Calculate the mean, median, and standard deviation of a 1D array.

In [19]:
array_stats = np.array([11, 56, 99, 83, 14, 56, 56, 14, 11, 21, 35, 11, 98, 66, 11, 25, 56, 2])
mean = np.mean(array_stats)
median = np.median(array_stats)
std_dev = np.std(array_stats)

print("Mean:", mean, "Median:", median, "Standard Deviation:", std_dev)

Mean: 40.27777777777778 Median: 30.0 Standard Deviation: 30.879345048386046


# Find the maximum and minimum values in a 2D array.

In [20]:
array_values = np.random.randint(1, 101, size=(5, 5))

max_value = np.max(array_values)
min_value = np.min(array_values)

print("2D Array:\n", array_values)
print("Max value:", max_value, "Min value:", min_value)

2D Array:
 [[ 84  88  62  70  60]
 [ 23  96   2  66 100]
 [ 98  57  16  86  60]
 [ 37  20  13  58  98]
 [ 16  32  87  58  45]]
Max value: 100 Min value: 2


# Generate an array of 1000 random numbers from a normal distribution with a mean of 0 and a standard deviation of 1.

In [22]:
normal_array = np.random.normal(0, 1, 1000)
print("Random numbers from normal distribution:\n", normal_array)

Random numbers from normal distribution:
 [-1.82627320e+00  1.13652958e+00 -6.06091274e-02  6.94544431e-01
 -8.10619003e-01  5.45992163e-01 -3.87050362e-01  2.28722102e+00
  9.13638004e-01  1.90629613e-01  4.18363641e-01  7.40882392e-01
 -1.37677970e+00 -1.01237178e+00  1.77544788e+00  7.47849247e-02
 -1.33605594e+00  1.39417416e+00  5.74789047e-03  1.23567461e+00
 -6.72050702e-01  5.09506833e-01  1.20613120e+00 -5.33185063e-02
  1.40887841e+00  4.13196906e-01  1.55753750e+00 -6.08426312e-02
  2.40463002e+00  8.79464763e-01 -3.86110418e-01  2.46722766e-01
 -8.61839396e-01  5.71820806e-01  6.59756138e-01 -4.75070747e-02
 -1.59558283e+00  1.53480727e+00  2.49096023e+00 -1.89303019e-01
 -1.37775681e+00  1.63910554e+00  7.41400753e-01 -8.84632605e-02
 -1.78916534e-01  1.35973264e+00 -1.39311724e-01  2.26046903e-01
  1.17616280e+00 -6.72792614e-01 -7.41712923e-01  9.17031181e-01
 -6.63326576e-01  1.09397956e+00  1.36802324e+00 -1.07894107e+00
  3.36439860e-01 -7.07480444e-01 -1.14826187e+00

# Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50

In [23]:
uniform_array = np.random.randint(10, 51, size=(5, 5))

print("2D Array (5x5) with random integers:\n", uniform_array)

2D Array (5x5) with random integers:
 [[48 35 46 34 24]
 [32 38 43 43 28]
 [18 38 22 49 18]
 [20 19 34 44 27]
 [29 39 40 17 36]]


# Calculate the cumulative sum of a 1D array.

In [24]:
array_sum = np.array([1, 2, 3, 4, 5])
cumulative_sum = np.cumsum(array_sum)

print("Cumulative sum of the array: \n", cumulative_sum)

Cumulative sum of the array: 
 [ 1  3  6 10 15]


# Compute the correlation coefficient matrix of a 2D array

In [25]:
array_corr = np.random.rand(5, 3)
correlation_matrix = np.corrcoef(array_corr, rowvar=False)

print("2D Array for correlation:\n", array_corr)
print("Correlation coefficient matrix:\n", correlation_matrix)

2D Array for correlation:
 [[2.96152755e-01 3.93465285e-01 7.73438879e-01]
 [9.17959334e-01 9.27337973e-02 2.15871063e-01]
 [5.49431218e-01 1.80967352e-01 1.93245507e-01]
 [7.48565039e-01 7.58879197e-01 1.66931654e-01]
 [2.74959134e-04 2.10796112e-01 2.96993204e-01]]
Correlation coefficient matrix:
 [[ 1.          0.12115778 -0.45838278]
 [ 0.12115778  1.          0.03578063]
 [-0.45838278  0.03578063  1.        ]]


# Compute the correlation coefficient matrix of a 2D array.

In [26]:
array_corr = np.random.rand(5, 3)
correlation_matrix = np.corrcoef(array_corr, rowvar=False)

print("2D Array for correlation:\n", array_corr)
print("Correlation coefficient matrix:\n", correlation_matrix)

2D Array for correlation:
 [[0.09404436 0.96915046 0.94663128]
 [0.32726536 0.12107453 0.78719057]
 [0.4770293  0.27960389 0.85549436]
 [0.73162468 0.76442012 0.54910298]
 [0.21666925 0.2670904  0.7808817 ]]
Correlation coefficient matrix:
 [[ 1.         -0.01549868 -0.83784502]
 [-0.01549868  1.         -0.0095968 ]
 [-0.83784502 -0.0095968   1.        ]]


# Simulate rolling a six-sided die 1000 times and count the frequency of each outcome.

In [27]:
rolls = np.random.randint(1, 7, 1000)
frequency = np.bincount(rolls)[1:]

print("Frequency of each outcome (1-6):", frequency)

Frequency of each outcome (1-6): [132 194 180 153 179 162]


# Note

==> np.random.randint is a function in the NumPy library that generates random integers. The function can be used to create arrays of random integers within a specified range. Here are some key details about np.random.randint.

==> By using np.random.randint, you can generate arrays of random integers for various purposes, such as simulating random events, creating test data, or populating matrices for mathematical operations.

==> np.bincount is a function in NumPy that counts the number of occurrences of each value in an array of non-negative integers. It returns an array where the value at each index i is the count of occurrences of i in the input array. This can be particularly useful for histogram-like operations.

==> np.corrcoef is a function in NumPy that calculates the Pearson correlation coefficients between rows or columns of a given input array. The Pearson correlation coefficient is a measure of the linear correlation between two variables, ranging from -1 (perfect negative correlation) to +1 (perfect positive correlation).

==> np.random.rand is a function in the NumPy library that generates an array of random numbers uniformly distributed between 0 (inclusive) and 1 (exclusive). The numbers are generated in a continuous uniform distribution.